---
- name: Installer et configurer Nginx
  hosts: all
  become: yes
  vars:
    http_port: 8080 # Port par défaut

  tasks:
    - name: Installer Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copier le fichier de configuration Nginx depuis le template
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - Restart Nginx

    - name: Déployer la page d'accueil personnalisée
      ansible.builtin.template:
        src: templates/html/index.html.j2
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted 
